ENV: development
DEBUG: True

SECRET_KEY: <SECRET KEY>

SQLALCHEMY_TRACK_MODIFICATIONS: False
SQLALCHEMY_DATABASE_URI: mysql+pymysql://<USER>:<PASSWORD>@<HOST>:<PORT>/<DB>
SQLALCHEMY_BINDS:
  postgres: postgresql://<USER>:<PASSWORD>@<HOST>:<PORT>/<DB>
